### ISSUE TITLE
Passing source_instance to enable_source

### ISSUE THREAD

**Issue by tchapi** [tchapi/pianette#6]
What is source_instance ?
How to do in a script like `pianette.enable_source gpio` ?

See : 

```
  # INFO : running command: pianette.enable_source gpio
Traceback (most recent call last):
  File "main.py", line 60, in <module>
    pianette.cmd.cmdloop()
  File "/Users/tchap/.pyenv/versions/3.3.6/lib/python3.3/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/Users/tchap/.pyenv/versions/3.3.6/lib/python3.3/cmd.py", line 217, in onecmd
    return func(arg)
  File "/Users/tchap/Documents/home/www/pianette/pianette/PianetteCmd.py", line 120, in do_game
    self.pianette.inputcmds(commands=commands, source="api")
  File "/Users/tchap/Documents/home/www/pianette/pianette/Pianette.py", line 168, in inputcmds
    self.cmd.onecmd(command)
  File "/Users/tchap/.pyenv/versions/3.3.6/lib/python3.3/cmd.py", line 217, in onecmd
    return func(arg)
  File "/Users/tchap/Documents/home/www/pianette/pianette/PianetteCmd.py", line 139, in do_pianette__enable_source
    self.pianette.enable_source(args)
TypeError: enable_source() missing 1 required positional argument: 'instance'
```

**Comment by tchapi** [comment]
https://github.com/tchapi/pianette/commit/e9f97a49b61cfa54d1a96ebaee07ab3b9d43b0f4 fixes this _a priori_
